
/**************************************************************
 *	
 *	backgroundSong, 8 bit, 11025Hz,
 *	1 channel, 213249 bytes/channel
 *	Total Size: 1 * 213249 + 4 (header) = 213293 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/labeall1/Desktop/backgroundSong.wav
 *	Time-stamp: Mon Dec 05 13:20:39 2016
 *	
 **************************************************************/

#ifndef __BACKGROUNDSONGH__
#define __BACKGROUNDSONGH__

#define BACKGROUNDSONGFREQ 11025
#define BACKGROUNDSONGLEN 213249

extern const unsigned char backgroundSong[213249];

#endif /* __BACKGROUNDSONGH__ */
