
/**************************************************************
 *	
 *	laugh, 8 bit, 11025Hz,
 *	1 channel, 19285 bytes/channel
 *	Total Size: 1 * 19285 + 4 (header) = 19329 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/labeall1/Desktop/Fall2017/CS2261/LauraBeall_FinalProject/laugh.wav
 *	Time-stamp: Mon Nov 28 15:10:59 2016
 *	
 **************************************************************/

#ifndef __LAUGHH__
#define __LAUGHH__

#define LAUGHFREQ 11025
#define LAUGHLEN 19285

extern const unsigned char laugh[19285];

#endif /* __LAUGHH__ */
